# Generated by Django 5.2.1 on 2025-07-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloud',
            name='pass_field',
            field=models.CharField(blank=True, db_column='pass', max_length=100, null=True),
        ),
    ]
